### ISSUE TITLE
Lỗi requests.request("POST", url, data=payload)

### ISSUE THREAD

**Issue by NguyenCongPhucBKHN** [bachtran2000/text-2-speech#1]
Dạ, anh ơi, em gặp lỗi này khi chạy code ạ:
![111](https://github.com/user-attachments/assets/fcc7c3c3-a518-4f94-9592-b7072a38d0db)

Có phải ZaloAI đã thay đổi API ko ạ ?

**Comment by barttran2k** [comment]
khả năng là zalo đã thay đổi API này rồi, em có thể dùng bản t2s của j2team nhé!

**Comment by NguyenCongPhucBKHN** [comment]
Dạ, em cảm ơn Anh nhiều ạ. Em muốn gọi hàm trong code mà ko sử dụng UI để code 1 phần mềm khác thì e có thể dùng source nào ạ ? Em cảm ơn Anh ạ.

**Comment by barttran2k** [comment]
Cái này thì nghe có vẻ khó, vì anh không còn làm trong mảng này nữa em ạ! Em chịu khó nghiên cứu thêm nhé!

**Comment by NguyenCongPhucBKHN** [comment]
Dạ vâng anh ạ. Em cảm ơn anh ạ!
